// flow-typed signature: 530e0889a943ac1088fb68ff17d968e6
// flow-typed version: <<STUB>>/d3fc-extent_v^2.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3fc-extent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3fc-extent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3fc-extent/build/d3fc-extent' {
  declare module.exports: any;
}

declare module 'd3fc-extent/build/d3fc-extent.min' {
  declare module.exports: any;
}

declare module 'd3fc-extent/src/date' {
  declare module.exports: any;
}

declare module 'd3fc-extent/src/linear' {
  declare module.exports: any;
}

declare module 'd3fc-extent/test/bundleSpec' {
  declare module.exports: any;
}

declare module 'd3fc-extent/test/dateSpec' {
  declare module.exports: any;
}

declare module 'd3fc-extent/test/linearSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3fc-extent/build/d3fc-extent.js' {
  declare module.exports: $Exports<'d3fc-extent/build/d3fc-extent'>;
}
declare module 'd3fc-extent/build/d3fc-extent.min.js' {
  declare module.exports: $Exports<'d3fc-extent/build/d3fc-extent.min'>;
}
declare module 'd3fc-extent/index' {
  declare module.exports: $Exports<'d3fc-extent'>;
}
declare module 'd3fc-extent/index.js' {
  declare module.exports: $Exports<'d3fc-extent'>;
}
declare module 'd3fc-extent/src/date.js' {
  declare module.exports: $Exports<'d3fc-extent/src/date'>;
}
declare module 'd3fc-extent/src/linear.js' {
  declare module.exports: $Exports<'d3fc-extent/src/linear'>;
}
declare module 'd3fc-extent/test/bundleSpec.js' {
  declare module.exports: $Exports<'d3fc-extent/test/bundleSpec'>;
}
declare module 'd3fc-extent/test/dateSpec.js' {
  declare module.exports: $Exports<'d3fc-extent/test/dateSpec'>;
}
declare module 'd3fc-extent/test/linearSpec.js' {
  declare module.exports: $Exports<'d3fc-extent/test/linearSpec'>;
}
