// flow-typed signature: 7b44e25d13931c6129a836f394ba4a12
// flow-typed version: <<STUB>>/d3kit_v^3.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3kit/dist/d3kit-es' {
  declare module.exports: any;
}

declare module 'd3kit/dist/d3kit' {
  declare module.exports: any;
}

declare module 'd3kit/dist/d3kit.min' {
  declare module.exports: any;
}

declare module 'd3kit/src/Base' {
  declare module.exports: any;
}

declare module 'd3kit/src/Base.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/chartlet' {
  declare module.exports: any;
}

declare module 'd3kit/src/chartlet.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/AbstractChart' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/AbstractChart.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/CanvasChart' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/CanvasChart.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/HybridChart' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/HybridChart.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/SvgChart' {
  declare module.exports: any;
}

declare module 'd3kit/src/charts/SvgChart.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/helper' {
  declare module.exports: any;
}

declare module 'd3kit/src/helper.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/layerOrganizer' {
  declare module.exports: any;
}

declare module 'd3kit/src/layerOrganizer.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/main' {
  declare module.exports: any;
}

declare module 'd3kit/src/main.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/AbstractPlate' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/AbstractPlate.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/CanvasPlate' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/CanvasPlate.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/DivPlate' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/DivPlate.spec' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/SvgPlate' {
  declare module.exports: any;
}

declare module 'd3kit/src/plates/SvgPlate.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3kit/dist/d3kit-es.js' {
  declare module.exports: $Exports<'d3kit/dist/d3kit-es'>;
}
declare module 'd3kit/dist/d3kit.js' {
  declare module.exports: $Exports<'d3kit/dist/d3kit'>;
}
declare module 'd3kit/dist/d3kit.min.js' {
  declare module.exports: $Exports<'d3kit/dist/d3kit.min'>;
}
declare module 'd3kit/src/Base.js' {
  declare module.exports: $Exports<'d3kit/src/Base'>;
}
declare module 'd3kit/src/Base.spec.js' {
  declare module.exports: $Exports<'d3kit/src/Base.spec'>;
}
declare module 'd3kit/src/chartlet.js' {
  declare module.exports: $Exports<'d3kit/src/chartlet'>;
}
declare module 'd3kit/src/chartlet.spec.js' {
  declare module.exports: $Exports<'d3kit/src/chartlet.spec'>;
}
declare module 'd3kit/src/charts/AbstractChart.js' {
  declare module.exports: $Exports<'d3kit/src/charts/AbstractChart'>;
}
declare module 'd3kit/src/charts/AbstractChart.spec.js' {
  declare module.exports: $Exports<'d3kit/src/charts/AbstractChart.spec'>;
}
declare module 'd3kit/src/charts/CanvasChart.js' {
  declare module.exports: $Exports<'d3kit/src/charts/CanvasChart'>;
}
declare module 'd3kit/src/charts/CanvasChart.spec.js' {
  declare module.exports: $Exports<'d3kit/src/charts/CanvasChart.spec'>;
}
declare module 'd3kit/src/charts/HybridChart.js' {
  declare module.exports: $Exports<'d3kit/src/charts/HybridChart'>;
}
declare module 'd3kit/src/charts/HybridChart.spec.js' {
  declare module.exports: $Exports<'d3kit/src/charts/HybridChart.spec'>;
}
declare module 'd3kit/src/charts/SvgChart.js' {
  declare module.exports: $Exports<'d3kit/src/charts/SvgChart'>;
}
declare module 'd3kit/src/charts/SvgChart.spec.js' {
  declare module.exports: $Exports<'d3kit/src/charts/SvgChart.spec'>;
}
declare module 'd3kit/src/helper.js' {
  declare module.exports: $Exports<'d3kit/src/helper'>;
}
declare module 'd3kit/src/helper.spec.js' {
  declare module.exports: $Exports<'d3kit/src/helper.spec'>;
}
declare module 'd3kit/src/layerOrganizer.js' {
  declare module.exports: $Exports<'d3kit/src/layerOrganizer'>;
}
declare module 'd3kit/src/layerOrganizer.spec.js' {
  declare module.exports: $Exports<'d3kit/src/layerOrganizer.spec'>;
}
declare module 'd3kit/src/main.js' {
  declare module.exports: $Exports<'d3kit/src/main'>;
}
declare module 'd3kit/src/main.spec.js' {
  declare module.exports: $Exports<'d3kit/src/main.spec'>;
}
declare module 'd3kit/src/plates/AbstractPlate.js' {
  declare module.exports: $Exports<'d3kit/src/plates/AbstractPlate'>;
}
declare module 'd3kit/src/plates/AbstractPlate.spec.js' {
  declare module.exports: $Exports<'d3kit/src/plates/AbstractPlate.spec'>;
}
declare module 'd3kit/src/plates/CanvasPlate.js' {
  declare module.exports: $Exports<'d3kit/src/plates/CanvasPlate'>;
}
declare module 'd3kit/src/plates/CanvasPlate.spec.js' {
  declare module.exports: $Exports<'d3kit/src/plates/CanvasPlate.spec'>;
}
declare module 'd3kit/src/plates/DivPlate.js' {
  declare module.exports: $Exports<'d3kit/src/plates/DivPlate'>;
}
declare module 'd3kit/src/plates/DivPlate.spec.js' {
  declare module.exports: $Exports<'d3kit/src/plates/DivPlate.spec'>;
}
declare module 'd3kit/src/plates/SvgPlate.js' {
  declare module.exports: $Exports<'d3kit/src/plates/SvgPlate'>;
}
declare module 'd3kit/src/plates/SvgPlate.spec.js' {
  declare module.exports: $Exports<'d3kit/src/plates/SvgPlate.spec'>;
}
