// flow-typed signature: 6c43ee6585be9b3f50803fc8344ff9ad
// flow-typed version: <<STUB>>/react-billboardjs_v^1.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-billboardjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-billboardjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-billboardjs/dist/react-billboard' {
  declare module.exports: any;
}

declare module 'react-billboardjs/dist/react-billboard.min' {
  declare module.exports: any;
}

declare module 'react-billboardjs/es/bb' {
  declare module.exports: any;
}

declare module 'react-billboardjs/es/BillboardChart' {
  declare module.exports: any;
}

declare module 'react-billboardjs/es/index' {
  declare module.exports: any;
}

declare module 'react-billboardjs/es/shapes' {
  declare module.exports: any;
}

declare module 'react-billboardjs/lib/bb' {
  declare module.exports: any;
}

declare module 'react-billboardjs/lib/BillboardChart' {
  declare module.exports: any;
}

declare module 'react-billboardjs/lib/index' {
  declare module.exports: any;
}

declare module 'react-billboardjs/lib/shapes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-billboardjs/dist/react-billboard.js' {
  declare module.exports: $Exports<'react-billboardjs/dist/react-billboard'>;
}
declare module 'react-billboardjs/dist/react-billboard.min.js' {
  declare module.exports: $Exports<'react-billboardjs/dist/react-billboard.min'>;
}
declare module 'react-billboardjs/es/bb.js' {
  declare module.exports: $Exports<'react-billboardjs/es/bb'>;
}
declare module 'react-billboardjs/es/BillboardChart.js' {
  declare module.exports: $Exports<'react-billboardjs/es/BillboardChart'>;
}
declare module 'react-billboardjs/es/index.js' {
  declare module.exports: $Exports<'react-billboardjs/es/index'>;
}
declare module 'react-billboardjs/es/shapes.js' {
  declare module.exports: $Exports<'react-billboardjs/es/shapes'>;
}
declare module 'react-billboardjs/lib/bb.js' {
  declare module.exports: $Exports<'react-billboardjs/lib/bb'>;
}
declare module 'react-billboardjs/lib/BillboardChart.js' {
  declare module.exports: $Exports<'react-billboardjs/lib/BillboardChart'>;
}
declare module 'react-billboardjs/lib/index.js' {
  declare module.exports: $Exports<'react-billboardjs/lib/index'>;
}
declare module 'react-billboardjs/lib/shapes.js' {
  declare module.exports: $Exports<'react-billboardjs/lib/shapes'>;
}
