// flow-typed signature: 0eb71c22bb82cce1e5229dc2434c048e
// flow-typed version: <<STUB>>/react-d3kit_v^2.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-d3kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-d3kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-d3kit/dist/react-d3kit.min' {
  declare module.exports: any;
}

declare module 'react-d3kit/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-d3kit/dist/react-d3kit.min.js' {
  declare module.exports: $Exports<'react-d3kit/dist/react-d3kit.min'>;
}
declare module 'react-d3kit/src/main.js' {
  declare module.exports: $Exports<'react-d3kit/src/main'>;
}
