// flow-typed signature: 3277b1051ff004a748f4eed3f799e642
// flow-typed version: <<STUB>>/react-jsx-highcharts_v^2.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jsx-highcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jsx-highcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jsx-highcharts/dist/react-jsx-highcharts' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/dist/react-jsx-highcharts.min' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaRangeSeries/AreaRangeSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaRangeSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSeries/AreaSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSplineRangeSeries/AreaSplineRangeSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSplineRangeSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSplineSeries/AreaSplineSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AreaSplineSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Axis/Axis' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Axis/AxisTitle' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Axis/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/AxisProvider/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BarSeries/BarSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BarSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BaseChart/BaseChart' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BaseChart/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BoxPlotSeries/BoxPlotSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BoxPlotSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BubbleSeries/BubbleSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/BubbleSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Chart/Chart' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Chart/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ChartProvider/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ColumnRangeSeries/ColumnRangeSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ColumnRangeSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ColumnSeries/ColumnSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ColumnSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Credits/Credits' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Credits/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Debug/Debug' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Debug/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ErrorBarSeries/ErrorBarSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ErrorBarSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/FunnelSeries/FunnelSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/FunnelSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Hidden/Hidden' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Hidden/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Highcharts3dChart/Highcharts3dChart' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Highcharts3dChart/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/HighchartsChart/HighchartsChart' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/HighchartsChart/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/HighchartsProvider/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/HighchartsSparkline/HighchartsSparkline' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/HighchartsSparkline/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Legend/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Legend/Legend' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Legend/LegendTitle' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/LineSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/LineSeries/LineSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Loading/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Loading/Loading' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Options3d/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Options3d/Options3d' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PieSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PieSeries/PieSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotBand/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotBand/PlotBand' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotBand/PlotBandLabel' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotLine/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotLine/PlotLine' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PlotLine/PlotLineLabel' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PolygonSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PolygonSeries/PolygonSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PyramidSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/PyramidSeries/PyramidSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/SankeySeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/SankeySeries/SankeySeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ScatterSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ScatterSeries/ScatterSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Series/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Series/Series' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/SeriesProvider/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/SplineSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/SplineSeries/SplineSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/StreamGraphSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/StreamGraphSeries/StreamGraphSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Subtitle/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Subtitle/Subtitle' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Title/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Title/Title' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Tooltip/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/Tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/TreemapSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/TreemapSeries/TreemapSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/WaterfallSeries/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/WaterfallSeries/WaterfallSeries' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/WithHighcharts/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/XAxis/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/XAxis/XAxis' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/YAxis/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/YAxis/YAxis' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ZAxis/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/components/ZAxis/ZAxis' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/index' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/boundContextHelper' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/cleanPropsBeforeUpdate' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/events' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/getModifiedProps' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/propTypeValidators' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/providedProps' {
  declare module.exports: any;
}

declare module 'react-jsx-highcharts/src/utils/removeProvidedProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jsx-highcharts/dist/react-jsx-highcharts.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/dist/react-jsx-highcharts'>;
}
declare module 'react-jsx-highcharts/dist/react-jsx-highcharts.min.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/dist/react-jsx-highcharts.min'>;
}
declare module 'react-jsx-highcharts/src/components/AreaRangeSeries/AreaRangeSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaRangeSeries/AreaRangeSeries'>;
}
declare module 'react-jsx-highcharts/src/components/AreaRangeSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaRangeSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSeries/AreaSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSeries/AreaSeries'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSplineRangeSeries/AreaSplineRangeSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSplineRangeSeries/AreaSplineRangeSeries'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSplineRangeSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSplineRangeSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSplineSeries/AreaSplineSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSplineSeries/AreaSplineSeries'>;
}
declare module 'react-jsx-highcharts/src/components/AreaSplineSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AreaSplineSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/Axis/Axis.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Axis/Axis'>;
}
declare module 'react-jsx-highcharts/src/components/Axis/AxisTitle.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Axis/AxisTitle'>;
}
declare module 'react-jsx-highcharts/src/components/Axis/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Axis/index'>;
}
declare module 'react-jsx-highcharts/src/components/AxisProvider/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/AxisProvider/index'>;
}
declare module 'react-jsx-highcharts/src/components/BarSeries/BarSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BarSeries/BarSeries'>;
}
declare module 'react-jsx-highcharts/src/components/BarSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BarSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/BaseChart/BaseChart.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BaseChart/BaseChart'>;
}
declare module 'react-jsx-highcharts/src/components/BaseChart/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BaseChart/index'>;
}
declare module 'react-jsx-highcharts/src/components/BoxPlotSeries/BoxPlotSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BoxPlotSeries/BoxPlotSeries'>;
}
declare module 'react-jsx-highcharts/src/components/BoxPlotSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BoxPlotSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/BubbleSeries/BubbleSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BubbleSeries/BubbleSeries'>;
}
declare module 'react-jsx-highcharts/src/components/BubbleSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/BubbleSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/Chart/Chart.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Chart/Chart'>;
}
declare module 'react-jsx-highcharts/src/components/Chart/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Chart/index'>;
}
declare module 'react-jsx-highcharts/src/components/ChartProvider/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ChartProvider/index'>;
}
declare module 'react-jsx-highcharts/src/components/ColumnRangeSeries/ColumnRangeSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ColumnRangeSeries/ColumnRangeSeries'>;
}
declare module 'react-jsx-highcharts/src/components/ColumnRangeSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ColumnRangeSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/ColumnSeries/ColumnSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ColumnSeries/ColumnSeries'>;
}
declare module 'react-jsx-highcharts/src/components/ColumnSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ColumnSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/Credits/Credits.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Credits/Credits'>;
}
declare module 'react-jsx-highcharts/src/components/Credits/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Credits/index'>;
}
declare module 'react-jsx-highcharts/src/components/Debug/Debug.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Debug/Debug'>;
}
declare module 'react-jsx-highcharts/src/components/Debug/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Debug/index'>;
}
declare module 'react-jsx-highcharts/src/components/ErrorBarSeries/ErrorBarSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ErrorBarSeries/ErrorBarSeries'>;
}
declare module 'react-jsx-highcharts/src/components/ErrorBarSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ErrorBarSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/FunnelSeries/FunnelSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/FunnelSeries/FunnelSeries'>;
}
declare module 'react-jsx-highcharts/src/components/FunnelSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/FunnelSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/Hidden/Hidden.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Hidden/Hidden'>;
}
declare module 'react-jsx-highcharts/src/components/Hidden/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Hidden/index'>;
}
declare module 'react-jsx-highcharts/src/components/Highcharts3dChart/Highcharts3dChart.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Highcharts3dChart/Highcharts3dChart'>;
}
declare module 'react-jsx-highcharts/src/components/Highcharts3dChart/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Highcharts3dChart/index'>;
}
declare module 'react-jsx-highcharts/src/components/HighchartsChart/HighchartsChart.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/HighchartsChart/HighchartsChart'>;
}
declare module 'react-jsx-highcharts/src/components/HighchartsChart/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/HighchartsChart/index'>;
}
declare module 'react-jsx-highcharts/src/components/HighchartsProvider/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/HighchartsProvider/index'>;
}
declare module 'react-jsx-highcharts/src/components/HighchartsSparkline/HighchartsSparkline.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/HighchartsSparkline/HighchartsSparkline'>;
}
declare module 'react-jsx-highcharts/src/components/HighchartsSparkline/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/HighchartsSparkline/index'>;
}
declare module 'react-jsx-highcharts/src/components/Legend/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Legend/index'>;
}
declare module 'react-jsx-highcharts/src/components/Legend/Legend.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Legend/Legend'>;
}
declare module 'react-jsx-highcharts/src/components/Legend/LegendTitle.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Legend/LegendTitle'>;
}
declare module 'react-jsx-highcharts/src/components/LineSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/LineSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/LineSeries/LineSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/LineSeries/LineSeries'>;
}
declare module 'react-jsx-highcharts/src/components/Loading/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Loading/index'>;
}
declare module 'react-jsx-highcharts/src/components/Loading/Loading.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Loading/Loading'>;
}
declare module 'react-jsx-highcharts/src/components/Options3d/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Options3d/index'>;
}
declare module 'react-jsx-highcharts/src/components/Options3d/Options3d.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Options3d/Options3d'>;
}
declare module 'react-jsx-highcharts/src/components/PieSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PieSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/PieSeries/PieSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PieSeries/PieSeries'>;
}
declare module 'react-jsx-highcharts/src/components/PlotBand/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotBand/index'>;
}
declare module 'react-jsx-highcharts/src/components/PlotBand/PlotBand.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotBand/PlotBand'>;
}
declare module 'react-jsx-highcharts/src/components/PlotBand/PlotBandLabel.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotBand/PlotBandLabel'>;
}
declare module 'react-jsx-highcharts/src/components/PlotLine/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotLine/index'>;
}
declare module 'react-jsx-highcharts/src/components/PlotLine/PlotLine.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotLine/PlotLine'>;
}
declare module 'react-jsx-highcharts/src/components/PlotLine/PlotLineLabel.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PlotLine/PlotLineLabel'>;
}
declare module 'react-jsx-highcharts/src/components/PolygonSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PolygonSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/PolygonSeries/PolygonSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PolygonSeries/PolygonSeries'>;
}
declare module 'react-jsx-highcharts/src/components/PyramidSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PyramidSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/PyramidSeries/PyramidSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/PyramidSeries/PyramidSeries'>;
}
declare module 'react-jsx-highcharts/src/components/SankeySeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/SankeySeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/SankeySeries/SankeySeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/SankeySeries/SankeySeries'>;
}
declare module 'react-jsx-highcharts/src/components/ScatterSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ScatterSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/ScatterSeries/ScatterSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ScatterSeries/ScatterSeries'>;
}
declare module 'react-jsx-highcharts/src/components/Series/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Series/index'>;
}
declare module 'react-jsx-highcharts/src/components/Series/Series.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Series/Series'>;
}
declare module 'react-jsx-highcharts/src/components/SeriesProvider/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/SeriesProvider/index'>;
}
declare module 'react-jsx-highcharts/src/components/SplineSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/SplineSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/SplineSeries/SplineSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/SplineSeries/SplineSeries'>;
}
declare module 'react-jsx-highcharts/src/components/StreamGraphSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/StreamGraphSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/StreamGraphSeries/StreamGraphSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/StreamGraphSeries/StreamGraphSeries'>;
}
declare module 'react-jsx-highcharts/src/components/Subtitle/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Subtitle/index'>;
}
declare module 'react-jsx-highcharts/src/components/Subtitle/Subtitle.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Subtitle/Subtitle'>;
}
declare module 'react-jsx-highcharts/src/components/Title/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Title/index'>;
}
declare module 'react-jsx-highcharts/src/components/Title/Title.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Title/Title'>;
}
declare module 'react-jsx-highcharts/src/components/Tooltip/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Tooltip/index'>;
}
declare module 'react-jsx-highcharts/src/components/Tooltip/Tooltip.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/Tooltip/Tooltip'>;
}
declare module 'react-jsx-highcharts/src/components/TreemapSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/TreemapSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/TreemapSeries/TreemapSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/TreemapSeries/TreemapSeries'>;
}
declare module 'react-jsx-highcharts/src/components/WaterfallSeries/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/WaterfallSeries/index'>;
}
declare module 'react-jsx-highcharts/src/components/WaterfallSeries/WaterfallSeries.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/WaterfallSeries/WaterfallSeries'>;
}
declare module 'react-jsx-highcharts/src/components/WithHighcharts/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/WithHighcharts/index'>;
}
declare module 'react-jsx-highcharts/src/components/XAxis/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/XAxis/index'>;
}
declare module 'react-jsx-highcharts/src/components/XAxis/XAxis.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/XAxis/XAxis'>;
}
declare module 'react-jsx-highcharts/src/components/YAxis/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/YAxis/index'>;
}
declare module 'react-jsx-highcharts/src/components/YAxis/YAxis.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/YAxis/YAxis'>;
}
declare module 'react-jsx-highcharts/src/components/ZAxis/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ZAxis/index'>;
}
declare module 'react-jsx-highcharts/src/components/ZAxis/ZAxis.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/components/ZAxis/ZAxis'>;
}
declare module 'react-jsx-highcharts/src/index.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/index'>;
}
declare module 'react-jsx-highcharts/src/utils/boundContextHelper.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/boundContextHelper'>;
}
declare module 'react-jsx-highcharts/src/utils/cleanPropsBeforeUpdate.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/cleanPropsBeforeUpdate'>;
}
declare module 'react-jsx-highcharts/src/utils/events.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/events'>;
}
declare module 'react-jsx-highcharts/src/utils/getModifiedProps.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/getModifiedProps'>;
}
declare module 'react-jsx-highcharts/src/utils/propTypeValidators.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/propTypeValidators'>;
}
declare module 'react-jsx-highcharts/src/utils/providedProps.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/providedProps'>;
}
declare module 'react-jsx-highcharts/src/utils/removeProvidedProps.js' {
  declare module.exports: $Exports<'react-jsx-highcharts/src/utils/removeProvidedProps'>;
}
