// flow-typed signature: 18bcd455d9dd7e0612b235556127ca84
// flow-typed version: <<STUB>>/@nivo/bar_v^0.33.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/bar/es/Bar' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/BarCanvas' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/BarItem' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/compute/common' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/compute/grouped' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/compute/index' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/compute/stacked' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/enhance' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/index' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/props' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/ResponsiveBar' {
  declare module.exports: any;
}

declare module '@nivo/bar/es/ResponsiveBarCanvas' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/Bar' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/BarCanvas' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/BarItem' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/compute/common' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/compute/grouped' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/compute/index' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/compute/stacked' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/enhance' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/index' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/props' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/ResponsiveBar' {
  declare module.exports: any;
}

declare module '@nivo/bar/lib/ResponsiveBarCanvas' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/bar/es/Bar.js' {
  declare module.exports: $Exports<'@nivo/bar/es/Bar'>;
}
declare module '@nivo/bar/es/BarCanvas.js' {
  declare module.exports: $Exports<'@nivo/bar/es/BarCanvas'>;
}
declare module '@nivo/bar/es/BarItem.js' {
  declare module.exports: $Exports<'@nivo/bar/es/BarItem'>;
}
declare module '@nivo/bar/es/compute/common.js' {
  declare module.exports: $Exports<'@nivo/bar/es/compute/common'>;
}
declare module '@nivo/bar/es/compute/grouped.js' {
  declare module.exports: $Exports<'@nivo/bar/es/compute/grouped'>;
}
declare module '@nivo/bar/es/compute/index.js' {
  declare module.exports: $Exports<'@nivo/bar/es/compute/index'>;
}
declare module '@nivo/bar/es/compute/stacked.js' {
  declare module.exports: $Exports<'@nivo/bar/es/compute/stacked'>;
}
declare module '@nivo/bar/es/enhance.js' {
  declare module.exports: $Exports<'@nivo/bar/es/enhance'>;
}
declare module '@nivo/bar/es/index.js' {
  declare module.exports: $Exports<'@nivo/bar/es/index'>;
}
declare module '@nivo/bar/es/props.js' {
  declare module.exports: $Exports<'@nivo/bar/es/props'>;
}
declare module '@nivo/bar/es/ResponsiveBar.js' {
  declare module.exports: $Exports<'@nivo/bar/es/ResponsiveBar'>;
}
declare module '@nivo/bar/es/ResponsiveBarCanvas.js' {
  declare module.exports: $Exports<'@nivo/bar/es/ResponsiveBarCanvas'>;
}
declare module '@nivo/bar/lib/Bar.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/Bar'>;
}
declare module '@nivo/bar/lib/BarCanvas.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/BarCanvas'>;
}
declare module '@nivo/bar/lib/BarItem.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/BarItem'>;
}
declare module '@nivo/bar/lib/compute/common.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/compute/common'>;
}
declare module '@nivo/bar/lib/compute/grouped.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/compute/grouped'>;
}
declare module '@nivo/bar/lib/compute/index.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/compute/index'>;
}
declare module '@nivo/bar/lib/compute/stacked.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/compute/stacked'>;
}
declare module '@nivo/bar/lib/enhance.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/enhance'>;
}
declare module '@nivo/bar/lib/index.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/index'>;
}
declare module '@nivo/bar/lib/props.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/props'>;
}
declare module '@nivo/bar/lib/ResponsiveBar.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/ResponsiveBar'>;
}
declare module '@nivo/bar/lib/ResponsiveBarCanvas.js' {
  declare module.exports: $Exports<'@nivo/bar/lib/ResponsiveBarCanvas'>;
}
